export const GET_EMPLOYEE_REQUESTED = "GET_EMPLOYEE_REQUESTED";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILED = "GET_EMPLOYEE_FAILED";

export const CREATE_EMPLOYEE_REQUESTED = "CREATE_EMPLOYEE_REQUESTED";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILED = "CREATE_EMPLOYEE_FAILED";

export const GET_EMPLOYEE_REQUESTED_BY_ID = "GET_EMPLOYEE_REQUESTED_BY_ID";
export const GET_EMPLOYEE_SUCCESS_BY_ID = "GET_EMPLOYEE_SUCCESS_BY_ID";
export const GET_EMPLOYEE_FAILED_BY_ID = "GET_EMPLOYEE_FAILED_BY_ID";

export const DELETE_EMPLOYEE_REQUESTED = "DELETE_EMPLOYEE_REQUESTED";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_REQUESTED = "EDIT_EMPLOYEE_REQUESTED";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const LOGIN_USER_REQUISTED = "LOGIN_USER_REQUISTED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER_REQUISTED = "LOGOUT_USER_REQUISTED";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const GET_USER_PROFILE_REQUESTED = "GET_USER_PROFILE_REQUESTED";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";

export const DELETE_MULTIPLE_EMPLOYEE = "DELETE_MULTIPLE_EMPLOYEE";

export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const ADD_CART_REQUESTED = "ADD_CART_REQUESTED";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILED = "ADD_CART_FAILED";

export const REMOVE_CART_REQUESTED = "REMOVE_CART_REQUESTED";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAILED = "REMOVE_CART_FAILED";

export const SIGNUP_USER_REQUISTED = "SIGNUP_USER_REQUISTED";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";

export const SEARCH_PRODUCT_REQUISTED = "SEARCH_PRODUCT_REQUISTED";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAILED = "SEARCH_PRODUCT_FAILED";
